# Generated by Django 3.1.2 on 2021-05-24 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_plasmaprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='rdt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
