# Generated by Django 3.1.2 on 2021-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='report',
            field=models.ManyToManyField(blank=True, to='patient.Report'),
        ),
    ]
