# Generated by Django 3.1.2 on 2021-05-24 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20210524_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
