# Generated by Django 3.1.2 on 2021-05-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skype',
            field=models.URLField(blank=True),
        ),
    ]
