# Generated by Django 3.1.2 on 2021-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
