# Generated by Django 3.1.2 on 2021-05-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skype',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
