# Generated by Django 3.1.2 on 2021-05-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='doctor_pics'),
        ),
    ]
