# Generated by Django 3.1.2 on 2021-05-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_appointment_consultation_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Close', 'Close')], max_length=10),
        ),
    ]
